
import java.util.HashMap;

/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/






/*
public char findTheDifference(String s, String t) {
    char c = 0;
    for (int i = 0; i < s.length(); ++i) {
            c ^= s.charAt(i);
    }
    for (int i = 0; i < t.length(); ++i) {
            c ^= t.charAt(i);
    }
    return c;
}*/

public class DifferenceOfStrings {
    public char findTheDifference(String s, String t) {
        HashMap<Character, Integer> set = new HashMap<>();
        for(int i = 0; i < s.length(); i++)
        {
            if(set.get(s.charAt(i)) == null)
            set.put(s.charAt(i), 1);
            else
            set.put(s.charAt(i), set.get(s.charAt(i))+1);
        }
        for(int i = 0; i < t.length(); i++)
        {
            if(set.get(t.charAt(i)) == null)
            return t.charAt(i);
            else if(set.get(t.charAt(i)) == 1)
            set.remove(t.charAt(i));
            else if(set.get(t.charAt(i)) > 1)
            set.put(t.charAt(i), set.get(t.charAt(i))-1);
        }
        return '\0';
    }
}
